### ISSUE TITLE
2023 02 15

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/community_wg#48]
# Community Agenda

Chair - Tammy McClellan – (MSFT)
Chair - Anne Currie - (Container Solutions)
Convenor - Sean Mcilroy – (LF)

## Date
2023-02-15 - 1600pm (BST) - [See your timezone](https://everytimezone.com/s/a8399b00)

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
The Community Working Group Meeting is recorded and will be made available after the call

### Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [ ] Convene & Roll Call 
- [ ] Approve agenda
- [ ] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/community_wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Meeting+Agenda%22)

## Meetup program
- [ ] https://github.com/Green-Software-Foundation/community-wg/issues/44
- [ ] Update on current status: search for organisers & Q1 events
- [ ] [New project view](https://github.com/orgs/Green-Software-Foundation/projects/20/views/3)
- [ ] Continue discussion on the roles we want GSF members to play in the meetup program vs non-GSF members.

> Anna to lead - Asim to drive discussion on roles

## Top level OKRs and GSF roadmap for 2023
- [ ] Review and discuss WG OKRs 
  - [ ] https://github.com/Green-Software-Foundation/oc/discussions/5

> Tammy to lead 

## [Project updates](https://github.com/Green-Software-Foundation/community-wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Project+update%22)
  - [ ] #30 Still on hold. Number of speakers: 82.
  - [ ] #31 Still on hold. Enrolled: 10074. Completed: 8816. (82%, Rating: 4.6)
  - [ ] #32 Still on hold. OKRs to be discussed.
  - [ ] #33 Still on hold.

> Anita to lead

## Operation details / next steps:
- [ ] exact tasks, meeting frequency, communication channels

> Tammy to lead

## Next meeting  [Decision]
15 Mar

## Adjourn 

-----------

### Action Item / Assigned to
- [ ] {notes to be added here}

**Comment by jawache** [comment]
Attended

**Comment by yuxin1234** [comment]
Attended

**Comment by tmcclell** [comment]
Attended

**Comment by alex-kroll** [comment]
Attended

**Comment by greenhsu123** [comment]
Attended.

**Comment by VirginieCorraze** [comment]
attended

**Comment by holanita** [comment]
Attended

**Comment by holanita** [comment]
@seanmcilroy29 and team – quick summary on today's CWG call (cc @jawache @tmcclell) 
- it has been decided to make the CWG call biweekly (same time)
- meetup governance questions have been discussed, see relevant topics [here](https://github.com/Green-Software-Foundation/meetup/discussions)
- need to review the new onboarding process and let everyone know how to onboard new people
- add to the next agenda the creation of the education sub-wg 
- https://github.com/Green-Software-Foundation/learn/issues/162 discussion to be continued in the other repo

**Comment by jawache** [comment]
Actions: 

- Nicole Corraze to be added to the Principles & Patterns project.
- Add DevRel Proposal to the next WG meeting agenda.

**Comment by VirginieCorraze** [comment]
CONFIDENTIAL & RESTRICTED

Sorry it should be Virginie Corraze (I was wrongly logged in) thank you

**Comment by holanita** [comment]
@VirginieCorraze no worries, I've invited you to the other repo using the right credentials and tagged you in the issue

**Comment by LiyaMath** [comment]
Attended

**Comment by seanmcilroy29** [comment]
Approved
