### ISSUE TITLE
2023 03 15

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/community_wg#51]
# Community Agenda

Chair - Tammy McClellan – (MSFT)
Chair - Anne Currie - (Container Solutions)
Convenor - Sean Mcilroy – (LF)

## Date
2023-03-15 - 1600pm (UTC) - [See your timezone](https://everytimezone.com/s/a8399b00)

### Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and it is the intention of the Joint Development Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

### Recordings
The Community Working Group Meeting is recorded and will be made available after the call

### Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [ ] Convene & Roll Call 
- [ ] Approve agenda
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/community_wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Meeting+Agenda%22)
- [ ] Internal Advocacy

## Meetup program
- [x] What do to with Earth day? check issue https://github.com/Green-Software-Foundation/learn/issues/142#issuecomment-1468360489

> Anna to lead 

## Education Sub-WG
- [x] Creation & purpose of a new education sub-wg
> Tammy/Asim to lead 

## DevRel Proposal
> Asim to lead

## Discussions
- [x] https://github.com/Green-Software-Foundation/community-wg/discussions/38
- [x] https://github.com/Green-Software-Foundation/community-wg/discussions/50

## Earth day - Sat, Apr 22, 2023
- [x] Activity options?
> Tammy to lead

## Top-level OKRs and GSF roadmap for 2023 updates
- [x] Review and discuss WG OKRs 
  - [x] https://github.com/Green-Software-Foundation/oc/discussions/5

> Tammy to lead 

## [Project updates](https://github.com/Green-Software-Foundation/community-wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Project+update%22)
  - [ ] #30 Still on hold. Number of speakers: 82.
  - [ ] #31 Still on hold. Enrolled: 10074. Completed: 8816. (82%, Rating: 4.6)
  - [ ] #32 Still on hold. OKRs to be discussed.
  - [ ] #33 Still on hold.

## Operation details / next steps:
- [ ] exact tasks, meeting frequency, communication channels

## Next meeting  [Decision]
29 Mar

## Adjourn 

-----------

### Action Item / Assigned to
- [ ] Earth Day: on the day we will post some tweets/posts throughout our platforms with the aim to push the training. @NAMRATA-WOKE  to look into this?
- [ ] Meetup: we will move away from Earth Day, @tadanna to get in touch with meetup team to see if we can use their promotion offer later in June for the World Environment Day. @jawache to start a discussion in the community WG forum around what is needed for the date in June.
- [ ] WG to come up with prize categories for students for the next Hackathon and get people to sponsor those prizes
- [ ] Green software experts program: @jawache  to follow up on having someone coming in to discuss how MVP is managed
- [ ] Writers project: there is a [writer repo](https://github.com/Green-Software-Foundation/writers) where everybody can add New Article Proposals.
- [ ] Internal advocacy: @jawache and @tmcclell to start a discussion topic about this

**Comment by jawache** [comment]
Attended

**Comment by yuxin1234** [comment]
Attended

**Comment by NAMRATA-WOKE** [comment]
Attended.

**Comment by greenhsu123** [comment]
Attended

**Comment by tadanna** [comment]
attended

**Comment by akshitbatra** [comment]
Attended.

**Comment by LiyaMath** [comment]
Attended.

**Comment by marcoshidalgonunes** [comment]
Attended

**Comment by alex-kroll** [comment]
Attended

**Comment by navveenb** [comment]
attended

**Comment by seanmcilroy29** [comment]
Approved
