### ISSUE TITLE
2023 03 29

### ISSUE THREAD

**Issue by tmcclell** [Green-Software-Foundation/community_wg#53]
## Date
2023-03-29 - 17:00pm UTC - See the time in your timezone https://everytimezone.com/s/a8399b00

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [ ] Convene & Roll Call 
- [x] Approve agenda
> Agenda reviewed - no objections - Agenda approved
- [x] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/community_wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Meeting+Agenda%22)
> No objections - Minutes approved
- [x] Internal Advocacy

## New Project Discussion
- [x] https://github.com/Green-Software-Foundation/community-wg/issues/92
> Comments added to Issue

## Meetup program updates
- [x] London event
> Comments added to Issue
- [x] [Upcoming events in April](https://github.com/orgs/Green-Software-Foundation/projects/20/views/3)
> Comments added to Issue
- [x] [World Environment Day in June (promotion from Meetup)](https://github.com/Green-Software-Foundation/meetup/issues/28) (latest comment at the bottom)
> Comments added to Issue

>Oleg and Asim

## Discussions 
- [x] https://github.com/Green-Software-Foundation/community-wg/discussions/38
> Comments added to Issue
- [x] [https://github.com/Green-Software-Foundation/community-wg/discussions/50
> Comments added to Issue
- [x]  https://github.com/Green-Software-Foundation/community-wg/discussions/52
> Comments added to Issue
- [x]  https://github.com/Green-Software-Foundation/community-wg/discussions/54
> Comments added to Issue
- [x]  Green Design Training  (UX) - Discussion topics
> Comments added to Issue

## Top-level OKRs and GSF roadmap for 2023 updates
- [ ] Review and discuss WG OKRs 
  - [x] https://github.com/Green-Software-Foundation/oc/discussions/5
> Comments added to Issue

## [Project updates](https://github.com/Green-Software-Foundation/community-wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Project+update%22)
  - [x] Green-Software-Foundation/oc#30 
  - [x] Green-Software-Foundation/oc#31 
  - [x] Green-Software-Foundation/community-wg#95 OKRs to be discussed.
  - [x] Green-Software-Foundation/gsf-admin#387

## GSF Newsletter
- [x] Submissions for the GSF newsletter 
> Namrata outlines the requirements for Newsletter submissions

## Next meeting  [Decision]
12 Apr
> agreed to maintain the current 1600 GMT slot

## AOB
- [x] New dedicated Community PM (Adam Jackson) has been hired and will be in place in the coming weeks

## Adjourn 
- [x] Motion to adjourn
No objections - Meeting closed
--------

## Action Items
- [x] Meetup: we will move away from Earth Day, @tadanna to contact the meetup team to see if we can use their promotion offer later in June for World Environment Day. @jawache to start a discussion in the community WG forum around what is needed for the date in June.
- [ ] WG to come up with prize categories for students for the next Hackathon and get people to sponsor those prizes
- [ ] Green software experts program: @jawache  to follow up on having someone come in to discuss how MVP is managed
- [ ] Writers project: there is a [writer repo](https://github.com/Green-Software-Foundation/writers) where everybody can add New Article Proposals.
- [ ] Internal advocacy: @jawache and @tmcclell to start a discussion topic about this

**Comment by camcash17** [comment]
Attended

**Comment by VirginieCorraze** [comment]
attended

**Comment by marcoshidalgonunes** [comment]
Attended

**Comment by yuxin1234** [comment]
Attended

**Comment by PindyBhullar** [comment]
attended

**Comment by seanmcilroy29** [comment]
Approved
