### ISSUE TITLE
2023 04 12

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/community_wg#55]
## Date
2023 04 12 - 16:00 GMT - See the time in your timezone https://everytimezone.com/s/a8399b00

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [ ] Convene & Roll Call 
- [ ] Approve agenda
- [ ] Approve [previous Meeting Minutes](https://github.com/Green-Software-Foundation/community_wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Meeting+Agenda%22)
- [ ] Internal Advocacy

## New Project Discussion
- [ ] https://github.com/Green-Software-Foundation/community-wg/issues/92
> WG to discuss and either raise questions on the ticket for next time or approve.

## Meetup program updates
- [ ] London event - Post event outcome
- [ ] [Upcoming events in April](https://github.com/orgs/Green-Software-Foundation/projects/20/views/3)
- [ ] [World Environment Day in June (promotion from Meetup)](https://github.com/Green-Software-Foundation/meetup/issues/28) (latest comment at the bottom)

>Oleg and Asim

## Discussions 
- [ ] https://github.com/Green-Software-Foundation/community-wg/discussions/38
- [ ] [https://github.com/Green-Software-Foundation/community-wg/discussions/50
- [ ] https://github.com/Green-Software-Foundation/community-wg/discussions/52
- [ ] https://github.com/Green-Software-Foundation/community-wg/discussions/54
- [ ] Green Design Training  (UX) - Discussion topics

## Top-level OKRs and GSF roadmap for 2023 updates
- [ ] Review and discuss WG OKRs 
  - [ ] https://github.com/Green-Software-Foundation/oc/discussions/5
> Tammy to lead 

## [Project updates](https://github.com/Green-Software-Foundation/community-wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Project+update%22)
  - [ ] Green-Software-Foundation/oc#30 
  - [ ] Green-Software-Foundation/oc#31 
  - [ ] Green-Software-Foundation/community-wg#95 OKRs to be discussed.
  - [ ] Green-Software-Foundation/gsf-admin#387

## GSF Newsletter
- [ ] Submissions for the GSF newsletter 
> Submissions to Namrata

## Next meeting  [Decision]
26 Apr

## AOB
- [ ] New dedicated Community PM (Adam Jackson) has been hired and will be in place in the coming weeks

## Adjourn 
- [ ] Motion to adjourn
--------

## Action Items
- [ ] Meetup: we will move away from Earth Day, @tadanna to get in touch with the meetup team to see if we can use their promotion offer later in June for the World Environment Day. @jawache to start a discussion in the community WG forum around what is needed for the date in June.
- [ ] WG to come up with prize categories for students for the next Hackathon and get people to sponsor those prizes
- [ ] Green software experts program: @jawache  to follow up on having someone coming in to discuss how MVP is managed
- [ ] Writers project: there is a [writer repo](https://github.com/Green-Software-Foundation/writers) where everybody can add New Article Proposals.
- [ ] Internal advocacy: @jawache and @tmcclell to start a discussion topic about this

**Comment by seanmcilroy29** [comment]
agreed
