### ISSUE TITLE
2023 08 02 - Green Software Community Working Group Agenda

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/community_wg#74]
## Date
2023 08 02 (2nd Aug 2023) - 3pm UTC - See the time in your timezone https://everytimezone.com/s/a8399b00

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Approve [Past Meeting Minutes](https://github.com/Green-Software-Foundation/community-wg/issues/67)
- [x] 1️⃣ Cover OKR Update 
- [x] 2️⃣ Meet our new **Content PM**
- [x] 3️⃣ Guest speaker _**Claire Smyth - Microsoft**_, to discuss the Contributors & Experts programme. 
- [x] 4️⃣ Request from @Sealjay https://github.com/Green-Software-Foundation/community-wg/issues/73
- [x] 5️⃣ Discussions Below
- [x] 6️⃣ Newsletter Call for Content
- [x] AOB
- [x] Close meeting

## [Project updates](https://github.com/Green-Software-Foundation/community-wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Project+update%22)
  - [ ] #30 
  - [ ] #31 
  - [ ] #32 OKRs to be discussed.
  - [ ] #33

## GSF Newsletter
- [ ] Submissions for the GSF newsletter 
> Submissions to Namrata

## Upcoming moments in time
- [ ] Q4 - Decarbonize Software
- [ ] Q4 - COP
- [ ] Q4 - Launch Contributors Programme, Initial Experts announced
- [ ] 2024 Q1 - Formal launch of Experts Programme
- [ ] 2024 Q1 - Impact Engine Hackathon

## Next meeting  [Decision]
16-Aug-2023 

## AOB
- [ ] Member questions or topic submissions?

## Adjourn 
- [ ] Motion to adjourn

**Comment by alex-kroll** [comment]
Attended

**Comment by adamj89** [comment]
Attended

**Comment by tmcclell** [comment]
Attended

**Comment by NAMRATA-WOKE** [comment]
Attended

**Comment by danielvaughan** [comment]
Attended

**Comment by Willmish** [comment]
Attended! :) Hi Community WG!

**Comment by PindyBhullar** [comment]
Attended

**Comment by yuxin1234** [comment]
Attended

**Comment by adamj89** [comment]
Action for @NAMRATA-WOKE to research Mastodon
