### ISSUE TITLE
2023 08 16 - Green Software Community Working Group Agenda

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/community_wg#76]
## Date
2023 08 16 (16th Aug 2023) - 3pm UTC - See the time in your timezone https://everytimezone.com/s/005304de
### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Approve **Past Meeting Minutes** https://github.com/Green-Software-Foundation/community-wg/issues/74
- [x] 1️⃣ Cover OKR Update 
- [x] 2️⃣ Proposal to close Slack channels https://github.com/Green-Software-Foundation/community-wg/issues/75
- [x] 3️⃣ Featured Member - Avanade
- [x] 4️⃣ Mastodon request from @Sealjay https://github.com/Green-Software-Foundation/community-wg/issues/73
- [x] 5️⃣ Discussions Below
- [x] 6️⃣ Newsletter Call for Content
- [x] AOB
- [x] Close meeting

## Discussions

- [ ] [Green Software Verified Facts](https://github.com/orgs/Green-Software-Foundation/discussions/47)

## [Project updates](https://github.com/Green-Software-Foundation/community-wg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Project+update%22)
  - [ ] #30 
  - [ ] #31 
  - [ ] #32 OKRs to be discussed.
  - [ ] #33

## GSF Newsletter
- [ ] Submissions for the GSF newsletter 
> Submissions to Namrata

## Upcoming moments in time
- [ ] Q4 - Decarbonize Software
- [ ] Q4 - COP
- [ ] Q4 - Launch Contributors Programme, Initial Experts announced
- [ ] 2024 Q1 - Formal launch of Experts Programme
- [ ] 2024 Q1 - Impact Engine Hackathon

## New Action Items 

---

### Avanade

* Chris Lloyd-Jones, Head of Open Technologies spoke about how they drove adoption of green software at Avanade
* Started as a grass-roots movement with a core team of 20-30 back in 2021. It has expanded significantly and there is now a dedicated sustainability hub
* They have been actively promoted the Green Software Practitioner program and now  have over 900 people certified
* Developed their own internal training programs including around SCI
* Q: How do you use the SCI?
  * Only approved metric for estimating carbon output
  * Built into a tool called Isotope
* Q: How did you you answer the “so what?” question?
  * Talked about linking it to company more widely - "Avande is a responsible business"
* Q: What should the GSF be learning from this?
  * Start with things that have a low barrier to entry
  * They started by throwing content out, later established lean coffees
  * Create a sense of belonging
* Q: Are people seeing the value of the efforts? How are the senior leadership responding to this?
  * Initially a large disconnect 
  * We demonstrated the value between sustainability and other understand business drivers
  * We spoke about the dollar value
  * More clients now care about sustainability - People initially weren’t thinking about carbon emissions of IT
  * Found simple language is very important. Compare to emissions of flights or kettles
  * Starting with measurement and monitoring to demonstrate how we are reducing
  * Find a killer facts - e.g. “Taking 230k vehicles off the road”
* Q: How did you engage with the broader regional teams?
  * Target an individual and provide practical support. Find someone who wants to be a local champion
  * Give them recognition for individual contributions

## Mastadon

* https://www.bbc.co.uk/rd/blog/2023-07-mastodon-distributed-decentralised-fediverse-activitypub
* Fosstodon full of open source engineers - People talking about sustainability
* Even republishing of content would be more useful than not doing anything at all
* Requires further discussion

---

## Next meeting  [Decision]
30-Aug-2023 

## AOB
- [ ] Member questions or topic submissions?
- [ ] @aecurrie Is there a GSF content review planned?

## Adjourn 
- [ ] Motion to adjourn

**Comment by Sealjay** [comment]
Attended!

**Comment by tholewis** [comment]
Attended.

**Comment by yuxin1234** [comment]
Attended.

**Comment by alex-kroll** [comment]
Attended

**Comment by PindyBhullar** [comment]
Attended

**Comment by trisha-03** [comment]
Attended

**Comment by kapokasa** [comment]
Attended
