### ISSUE TITLE
2023-10-11 - Green Software Community Working Group Agenda

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/community_wg#86]
## Date
2023-10-11 - 3pm UTC - See the time in your timezone https://everytimezone.com/s/cc45bdd5

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available. Please review the [Linux Foundation privacy policy](https://www.linuxfoundation.org/legal/privacy-policy)

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [ ] Convene & Roll Call (5mins)
- [ ] Review Meeting Notices (see above)
- [x] Approve [Past Meeting Minutes](https://github.com/Green-Software-Foundation/community-wg/issues/84) & review actions
- [x] OKR & KPI update
- [x] Update from @NAMRATA-WOKE on Decarb registrations including reg ratio
- [x] Follow-up on https://github.com/Green-Software-Foundation/oc/issues/46
- [x] Follow-up on https://github.com/Green-Software-Foundation/community-wg/issues/83
- [x] https://github.com/Green-Software-Foundation/community-wg/issues/81
- [x] https://github.com/Green-Software-Foundation/policy-wg/issues/59
- [ ] Discussion [Green Software Verified Facts](https://github.com/orgs/Green-Software-Foundation/discussions/47)
- [ ] - [ ] Reviewing open [Oversight Committee issues](https://github.com/Green-Software-Foundation/oc/issues?q=is%3Aissue+is%3Aopen+label%3A%22Community+WG%22)
- [ ] Newsletter call for content
- [ ] AOB, Q&A & Adjourn (5mins)

## Upcoming moments in time
- 16 November 2023 - Decarbonize Software
- 30 Nov – 12 Dec 2023 - COP
- Q4 2023 - Launch Champions programme, Initial Experts announced
- 2024 Q1 - Formal launch of Experts Programme
- 2024 Q1 - Impact Engine Hackathon

## Any Other Business
- [ ] ...

## Decisions
- [ ] ...

## Action Items
- [ ] ...

**Comment by PindyBhullar** [comment]
Attended

**Comment by alexander-kroll** [comment]
Attended

**Comment by yuxin1234** [comment]
Attended

**Comment by franziska-warncke** [comment]
Attended

**Comment by Willmish** [comment]
Attended !

**Comment by greenhsu123** [comment]
Attended

**Comment by tholewis** [comment]
Attended.

**Comment by russelltrow** [comment]
# Meeting Notes

## OKRs

### Meetups

* @adamj89 what is being discussed? What feedback are we getting?

## [Green Software Maturity Matrix](https://github.com/Green-Software-Foundation/oc/issues/46)

* There is an early draft available
  * https://docs.google.com/document/d/1wa2lliXQeH6HE1JHqwjTFuVndRUXzxGlbYXRtTQxF5o/edit
* The Working Group officially approved the project
* Next step is to allow the Oversight Committee the chance to comment/object

## [Consider supporting ClimateHack 2023 (co-organised by UCL's AI Society)](https://github.com/Green-Software-Foundation/community-wg/issues/83)

* Requires further discussion with the GSF, especially around budgets.
* @greenhsu123 asked can we support other university events?
  * The GSF need to discuss the strategy for engaging with Higher Education more broadly.
  * Discussion on what resources we have that we could provide outside of money
* @tholewis is working on course curriculum that is Open Source that is based on the GSF materials for Green Software Engineering
  * Will be Open Source on GitHub
  * Expect to be available in November
  * It will contain reference to the Carbon Aware SDK.
    * @Willmish said they are currently having internal discussions on next steps for the project and improving ease of getting started is a top priority so far 

## [Giscus](https://github.com/Green-Software-Foundation/community-wg/issues/81)

* Questions for Chris Lloyd-Jones added to ticket

## [Roundtable](https://github.com/Green-Software-Foundation/policy-wg/issues/59)

* Support for the idea. The group sees potential to apply the concept to other groups and areas.

# Actions

- [x] @russelltrow to notify the OC of the GSMM project approval and give them opportunity to comment
- [x] @aecurrie & @russelltrow to organise project initiation once approved
- [ ] @adamj89 & @NAMRATA-WOKE to sync on the UCL ClimateHack before next meeting
- [ ] @NAMRATA-WOKE to speak with Asim & Sean about budgets for HE sponsorship
- [x] @russelltrow reach out to @syzmon to speak about if the GSF can support with CASDK enablement material
- [x] @Willmish to open a thread on [GSF Discussions](https://github.com/orgs/Green-Software-Foundation/discussions/categories/community-working-group) about higher education engagement
- [x] @russelltrow to discuss Roundtable concept with GSF team and determine next steps

**Comment by Willmish** [comment]
Discussion created here: https://github.com/orgs/Green-Software-Foundation/discussions/72 @greenhsu123 @tholewis @tmcclell @aecurrie please leave your thoughts and ideas mentioned during the call there!
