### ISSUE TITLE
2023-10-25 - Green Software Community Working Group Agenda

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/community_wg#88]
## Date
2023-10-25 - 3pm UTC - See the time in your timezone https://everytimezone.com/s/cc45bdd5

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available. Please review the [Linux Foundation privacy policy](https://www.linuxfoundation.org/legal/privacy-policy)

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review & Approve [Past Meeting Minutes](https://github.com/Green-Software-Foundation/community-wg/issues/86)
- [x] OKR & KPI update
- [x] Follow-up on [Thoughts on University engagement (supporting Student events, providing curriculum templates)](https://github.com/orgs/Green-Software-Foundation/discussions/72)
  - [ ] https://github.com/Green-Software-Foundation/community-wg/issues/83
  - [ ] How might we help La Cité Collégial in Canada?
- [ ] Follow-up on https://github.com/Green-Software-Foundation/community-wg/issues/81
- [ ] Follow-up on https://github.com/Green-Software-Foundation/gsf-admin/issues/369
- [ ] Discussion [Green Software Verified Facts](https://github.com/orgs/Green-Software-Foundation/discussions/47)
- [ ] Reviewing open [Oversight Committee issues](https://github.com/Green-Software-Foundation/oc/issues?q=is%3Aissue+is%3Aopen+label%3A%22Community+WG%22)
- [ ] AOB, Q&A & Adjourn (5mins)

## Projects

* [Green Maturity Matrix](https://github.com/Green-Software-Foundation/oc/issues/46) ![proposal](https://img.shields.io/badge/Proposal-E7E9E7)
* [Champions/Speakers](https://github.com/Green-Software-Foundation/speakers) ![incubation](https://img.shields.io/badge/Incubation-A2CF62)
* [Meetup](https://github.com/Green-Software-Foundation/meetup) ![incubation](https://img.shields.io/badge/Incubation-A2CF62)
* [Green Software Patterns](https://github.com/Green-Software-Foundation/patterns) ![incubation](https://img.shields.io/badge/Incubation-A2CF62)
* [Green Software Practitioner course](https://github.com/Green-Software-Foundation/learn) ![incubation](https://img.shields.io/badge/Incubation-A2CF62)
* [Decarbonize Software event](https://github.com/Green-Software-Foundation/decarbonize-software-event)
* [Carbon Hack 24](https://github.com/Green-Software-Foundation/carbonhack-event)

## Upcoming moments in time

- 27 October 2023 - Green Maturity Matrix project approval
- 16 November 2023 - Decarbonize Software
- 16 November 2023 - Launch Champions programme, Initial Experts announced
- 30 Nov – 12 Dec 2023 - COP
- 26 Feb - 15 March 2024 - Carbon Hack 24
- Q1 2024 Q1 - Formal launch of Experts Programme

## Any Other Business
- [ ] ...

**Comment by PindyBhullar** [comment]
Hi @russelltrow can we also discuss the GSF exam results data?

**Comment by PindyBhullar** [comment]
Attended

**Comment by yuxin1234** [comment]
Attended

**Comment by Sophietn** [comment]
Attended

**Comment by tholewis** [comment]
Attended!

**Comment by danielvaughan** [comment]
Attended

**Comment by ikolaxis** [comment]
Attended

**Comment by rubydickinson19** [comment]
Attended

**Comment by russelltrow** [comment]
# Meeting Notes

## Attendees

* @rubydickinson19 from Avanade is joining us to support @Sealjay 

## OKRs

* Patterns
  * 50 live
  * Discussion on the importance of impact of volume
* Principles
  * Avanade has only 1,000 completions
  * UBS is growing fast with over 130
* Experts
  * @tmcclell suggested the criteria for selecting Experts should be discussed at the Oversight Committee

## [Higher Education](https://github.com/orgs/Green-Software-Foundation/discussions/72)

* Discussed the need for a GSF strategy in regards to Higher Education - at least a “cafeteria plan”
* @tholewis is [developing a curriculum ](https://github.com/orgs/Green-Software-Foundation/discussions/72#discussioncomment-7316931)
  * @PindyBhullar offered to connect @tholewis with the University of Southampton to trial anything
* @PindyBhullar raised a question on whether the GSF should have an cross-cutting learning initiative supporting all projects rather than just a single project under the WG. 
  *  Discussion on the idea of moving from just Training to Enablement which supports all of our users (from students to adopters of our software projects)
* @aecurrie asked what we know about our Members needs?
  * Not enough at the moment but @NAMRATA-WOKE is working hard to connect with our Members and understand them and their needs more
  * Suggestions of running a survey across the members
  * @NAMRATA-WOKE would be happy to share more on her strategy for engaging, understanding and supporting
  * Request that there is a new standing agenda item where Namrata shares her findings
* Discussion on working with HE not just to educate but prepare graduates for the future
  * Pindy: "Talk about the type of roles that are coming to the market not just the market of today - Future sustainability roles"
  * Thomas: “One other vector for us to consider is "how do you enable students to get jobs?" in addition to training them. I was the Academic Advocacy lead for Cloud Advocacy and EVERY learning institution wanted to know how we could support that.”
* Proposal that @tholewis would pull together some ideas on a Higher Education strategy and present back to the group
  * This could lead to a new GSF Project made up of students + seasoned practitioners
  * "I believe students of academic institutions that are members of the foundation can contribute to our WGs and Projects. With this set up, they get the guidance and support of the Computer Science / ICT departments that are driving that relationship and can help connect the dots between what they're studying and the practical experience they're gaining."

 ## Actions

- [ ] @adamj89 @tmcclell add GSF Experts criteria to a future OC agenda
- [ ] @tholewis @PindyBhullar create a project proposal for a GSF Higher Education strategy. Present back on Wednesday 22 November
- [x] @russelltrow add standing agenda item for @NAMRATA-WOKE to share a Member Org check-in report

Thank you all!
